"""
Django settings for netremor_dashboard project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR         = Path(__file__).resolve().parent.parent
DATAFILES_DIR    = Path.joinpath(BASE_DIR, "data-files")
IMUFILES_DIR     = Path.joinpath(BASE_DIR, "imu-files")
TREMOR_FILES_DIR = Path.joinpath(BASE_DIR, "tremor-files")

SENSOR_CHOICES = [
    ("accelerometer", "Accelerometer"),
    ("gyroscope", "Gyroscope"),
]

# IMU parsing and tremor computation constants:
DEFAULT_DELTA_T               = 30
DEFAULT_TREMOR_LOW_PASS_FREQ  = 2
DEFAULT_TREMOR_HIGH_PASS_FREQ = 10
DEFAULT_TREMOR_HOP_SECONDS    = 1
DEFAULT_TREMOR_WINDOW_SECONDS = 3


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i8um7+i47%m67y_gp(kvu6_#unxp*pt&9i&cg#4zjrb8l@*eo3'

# REDIRECT TRAFFIC FROM HTTP TO HTTPS:
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SECURE_SSL_REDIRECT = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ["https://netremor.oriontech.es", "http://netremor.oriontech.es"]

LOGIN_URL = "/login/"

# Application definition

INSTALLED_APPS = [
    "endpoint.apps.EndpointConfig",
    "dashboard.apps.DashboardConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'netremor_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # included to override admin's templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'netremor_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "netremor_db",
        "USER": "dashboard_usu",
        "PASSWORD": "Mt4?FmQsj$nXCp6t",
        "HOST": "localhost"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-en'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FILES = None
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024

ALLOWED_EMAIL_DOMAINS = ["upm.es", "csic.es", "alumnos.upm.es", "car.upm-csic.es"]

VERIFICATION_CODE_LENGTH = 50